services:
  maven:
    image: maven:3.9-eclipse-temurin-17
    container_name: CI_CD_maven
    volumes:
      - .:/app
      - maven_cache:/root/.m2
    working_dir: /app
    command: mvn clean install
    environment:
      - MAVEN_CONFIG=/root/.m2
    networks:
      - infra-network

  db:
    image: postgres:15
    container_name: CI_CD_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - infra-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: CI_CD_elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - infra-network

  sonarqube:
    image: sonarqube:9.9.2-community
    container_name: CI_CD_sonarqube
    ports:
      - "9001:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - infra-network
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: CI_CD_jenkins
    privileged: true
    user: root
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - infra-network

networks:
  infra-network:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch_data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  jenkins_home:
  maven_cache: