spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev-bank-db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    open-in-view: false

  liquibase:
    change-log: classpath:db/migration/changelog.yml
    enabled: true
    default-schema: public
    drop-first: false
    contexts: dev
    database-change-log-table: DATABASECHANGELOG
    database-change-log-lock-table: DATABASECHANGELOGLOCK

  elasticsearch:
    uris: ${ELASTICSEARCH_URI:localhost:9200}
    connection-timeout: 5s
    socket-timeout: 30s
    username:
    password:

  security:
    jwt:
      expiration-time: 8640000000000000
      secret-key: "Your32CharacterLongBase64EncodedSecretKeydvererberbbe"

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  packages-to-scan: com.bankapp.server.controller
  paths-to-match: /api/**

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE